// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZiEFxVXQ6k4RPNcKMUrBVpFMqoaMj1w',
    appId: '1:1052914099246:web:6454427b7da04f04af2bbf',
    messagingSenderId: '1052914099246',
    projectId: 'quotegenerator-d3b6b',
    authDomain: 'quotegenerator-d3b6b.firebaseapp.com',
    storageBucket: 'quotegenerator-d3b6b.appspot.com',
    measurementId: 'G-BJ92HDQ82Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCadpY6aUFTAYtsVeduLE6TNDlGPzg5Su0',
    appId: '1:1052914099246:android:1434fb9b34d2011caf2bbf',
    messagingSenderId: '1052914099246',
    projectId: 'quotegenerator-d3b6b',
    storageBucket: 'quotegenerator-d3b6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMA2BY5-32rUeEoRIXS596d1GdEX64yc',
    appId: '1:1052914099246:ios:6b506b41ffd953a5af2bbf',
    messagingSenderId: '1052914099246',
    projectId: 'quotegenerator-d3b6b',
    storageBucket: 'quotegenerator-d3b6b.appspot.com',
    iosBundleId: 'com.example.quoteGenerator',
  );
}
